CREATE TABLE "lesson_reflections" (
  "id" text PRIMARY KEY,
  "lesson_plan_id" text NOT NULL,
  "user_id" text NOT NULL,
  "reflection_date" text NOT NULL,
  "objectives_met" text,
  "student_understanding" text,
  "evidence_support" text,
  "students_not_meeting_objectives" text,
  "misconceptions_difficulties" text,
  "assessment_effective" text,
  "content_suitable" text,
  "strategies_engaging" text,
  "students_on_task" text,
  "differentiation_effective" text,
  "future_improvements" text,
  "long_term_goals" text,
  "behavioral_issues" text,
  "student_opportunities" text,
  "teaching_insights" text,
  "overall_rating" integer,
  "time_management" text,
  "student_engagement_level" text,
  "next_steps" text,
  "created_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP
); 