import { sql } from "drizzle-orm"
import { text, integer, sqliteTable } from "drizzle-orm/sqlite-core"

export const lessonPlans = sqliteTable("lesson_plans", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  subject: text("subject").notNull(),
  grade: text("grade").notNull(),
  topic: text("topic"),
  content: text("content").notNull(),
  duration: text("duration").notNull(),
  objectives: text("objectives"),
  materials: text("materials"),
  overview: text("overview"),
  standards: text("standards"),
  vocabulary: text("vocabulary"),
  homework: text("homework"),
  extensions: text("extensions"),
  pedagogical_strategy: text("pedagogical_strategy"),
  differentiation_strategies: text("differentiation_strategies"),
  grouping_strategy: text("grouping_strategy"),
  assessment_approach: text("assessment_approach"),
  curriculum_standards: text("curriculum_standards"),
  user_id: text("user_id").notNull(),
  created_at: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updated_at: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
})

export const crossCurricularPlans = sqliteTable("cross_curricular_plans", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  theme: text("theme").notNull(),
  description: text("description"),
  grade_range: text("grade_range").notNull(),
  duration_days: integer("duration_days"),
  subjects_included: text("subjects_included").notNull(),
  subject_connections: text("subject_connections"),
  central_question: text("central_question"),
  learning_objectives: text("learning_objectives"),
  plan_content: text("plan_content").notNull(),
  culminating_activities: text("culminating_activities"),
  assessment_strategies: text("assessment_strategies"),
  materials_needed: text("materials_needed"),
  tags: text("tags"),
  is_public: integer("is_public", { mode: "boolean" }).default(false),
  created_by: text("created_by"),
  created_at: text("created_at").default(sql`CURRENT_TIMESTAMP`),
  updated_at: text("updated_at").default(sql`CURRENT_TIMESTAMP`),
})

export const crossCurricularReflections = sqliteTable("cross_curricular_reflections", {
  id: text("id").primaryKey(),
  plan_id: text("plan_id").notNull().references(() => crossCurricularPlans.id),
  user_id: text("user_id").notNull(),
  reflection_date: text("reflection_date").notNull(),
  objectives_met: text("objectives_met"),
  student_understanding: text("student_understanding"),
  evidence_support: text("evidence_support"),
  students_not_meeting_objectives: text("students_not_meeting_objectives"),
  misconceptions_difficulties: text("misconceptions_difficulties"),
  assessment_effective: text("assessment_effective"),
  content_suitable: text("content_suitable"),
  strategies_engaging: text("strategies_engaging"),
  students_on_task: text("students_on_task"),
  differentiation_effective: text("differentiation_effective"),
  future_improvements: text("future_improvements"),
  long_term_goals: text("long_term_goals"),
  behavioral_issues: text("behavioral_issues"),
  student_opportunities: text("student_opportunities"),
  teaching_insights: text("teaching_insights"),
  overall_rating: integer("overall_rating"),
  time_management: text("time_management"),
  student_engagement_level: text("student_engagement_level"),
  next_steps: text("next_steps"),
  created_at: text("created_at").default(sql`CURRENT_TIMESTAMP`),
  updated_at: text("updated_at").default(sql`CURRENT_TIMESTAMP`),
})

export const strands = sqliteTable("strands", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  description: text("description"),
  sort_order: integer("sort_order").notNull(),
}) 